### PR TITLE
Fix click event target, now works with shadow dom

### PR DESCRIPTION
**Pull request by donflopez**

### CODE REVIEW

**Comment by euvl** [comment]
why would you want to rename the project and change repo url in bower file to your fork ? oO

**Comment by donflopez** [comment]
Ohh! Sorry, we really need it and we publish it in bower until this PR was merged, but I don't think that the PR could have the changes too.

I only want do the PR with the first commit, not the others. How can I change it?

I'm really sorry about this @euvl.

**Comment by bmcorser** [comment]
:+1: for the fix

You could rebase against `visionmedia:master` like this:
```
git remote add visionmedia git@github.com:visionmedia/page.js.git
git fetch visionmedia
git rebase -i visionmedia/master
```

This should open a text editor and you can just delete the line with 6730238, then push here

Good luck `:)`

**Comment by StatelessCat** [comment]
Thanks for the fix. This is an especially useful improvement for [PolymerElements/polymer-starter-kit](https://github.com/PolymerElements/polymer-starter-kit). 
Without this patch, we cannot use an `<a href='/users/xxx'>` inside a Polymer Custom Element template when `window.Polymer.dom = 'shadow';` is enabled. 

Hope this PR or [this PR](https://github.com/visionmedia/page.js/pull/284) will be merged in page.js/master.

**Comment by donflopez** [comment]
@bmcorser thanks for your help!

I've made some improvements to work in others browsers like Firefox.

@StatelessCat this is why we are made our clone in bower, we need that! ;)

**Pull request closed without merging**
