### PR TITLE
Switch to rollup for the build

### LINKED ISSUE #444: Clojure compiler warning
When compiling JS which uses page.js it has the following annoying warning:

```
node_modules/page/page.js:1: WARNING - Suspicious code. The result of the 'not' operator is not being used.
!function(e){if("object"==typeof exports&&"undefined"!=typeof module)module.exports=e();else if("function"==typeof define&&define.amd)define([],e);else{var f;"undefined"!=typeof window?f=window:"undefined"!=typeof global?f=global:"undefined"!=typeof self&&(f=self),f.page=e()}}(function(){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
```
Would be cool to replace "!function(...){..}(...)" by "(function(...){...})(...)".

### PR DESCRIPTION
**Pull request by matthewp**
This switches to using rollup for the build. This fixes #444 among other
things.

### CODE REVIEW

**Comment by matthewp** [comment]
Shaves about 2k off of the bundle size.

**Comment by matthewp** [comment]
cc @paulocoghi

**Comment by paulocoghi** [comment]
Excellent!

Also, these removed kbs can make room for any new features without leaving the library larger than usual.

**Comment by paulocoghi** [comment]
I have only one suggestion. In my opinion, it would be interesting to offer a minified version, `page.min.js`, using `rollup-plugin-uglify`, this way:

```js
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve';
import uglify from 'rollup-plugin-uglify';
import { minify } from 'uglify-es';

export default {
  input: 'index.js',
  output: {
    file: 'page.min.js',
    format: 'umd',
    name: 'page'
  },
  plugins: [
    nodeResolve({
      jsnext: true,
      main: true
    }),
    commonjs({
      include: ['node_modules/**', '**']
    }),
    uglify( {}, minify )
  ]
};
```

**Comment by paulocoghi** [comment]
The code above (for minified version) can reside in a new (additional) file `rollup.config-min.js`, and in `package.json`, you can change the "make" line to:

```json
"make": "rollup -c rollup.config.js && rollup -c rollup.config-min.js"
```

**Comment by matthewp** [comment]
@paulocoghi Let's discuss the minify idea in a new issue. I'd like to take some time to discuss it a bit and see what other libraries are doing these days (not sure if most are including a minified version or not. Does any include a gzipped version too?), and I don't want that to block this PR since it fixes issues like #458

**Comment by vagran** [comment]
BTW I opened #444 because it was not fully minified and I included page.js among other scripts for minification by closure compiler.

**Pull request merged**
