### PR TITLE
make sure _onpopstate is defined in non-browser envs

### LINKED ISSUE #501: Cannot read property 'bind' of undefined
After upgrade to `1.10.0` i got an error: 
image

https://github.com/visionmedia/page.js/blob/v1.10.0/index.js#L53

### PR DESCRIPTION
**Pull request by flootr**
fixes #501

### CODE REVIEW

**Comment by matthewp** [comment]
I really want to keep the test coverage up and not accept PRs that reduce it. If you are able to add a test which fixes this decrease that's great. Otherwise I'll get to it eventually. Thanks again for the PR!

**Comment by flootr** [comment]
@matthewp fair point, I'll see if I can get to it soon 👍

**Comment by flootr** [comment]
@matthewp I've a hard time creating tests for this. If you don't mind I'd appreciate if you would take this over.

**Comment by matthewp** [comment]
Let's just merge.

**Pull request merged**
