### PR TITLE
small fix to prevent an error in nodejs

### PR DESCRIPTION
**Pull request by PaulMaly**

### CODE REVIEW

**Comment by PaulMaly** [comment]
Really? I gues not. If document is undefined, then this.title will be equal false, if document defined this.title = document.title.

You able to check it yourself: https://jsfiddle.net/t5dnmjdg/

**Comment by paulocoghi** [comment]
You are right :)

Thanks to take time and explain it! And sorry for my mistake.

**Comment by PaulMaly** [comment]
Don't worry. )) Could you please aprove this fix? We use Pagejs and want to go back to original repo soon as we can.

**Comment by paulocoghi** [comment]
I am not an authorized maintainer, but also a developer and user of Page.js.

My pull request is pending, too.

**Comment by rstacruz** [comment]
`document` is needed in many places, not just this one...so this wouldn't really "fix" node.js usage with just that. Nonetheless it's one step closer to getting page.js isomorphic-ready.

**Pull request merged**
