### PR TITLE
Decode path parameters once

### PR DESCRIPTION
**Pull request by heymagurany**
This is another fix for #306. The only real change I made was to remove the second call to `decodeURLEncodedURIComponent`. The changes to page.js are the results of running `npm run make`.

### CODE REVIEW

**Comment by matthewp** [comment]
Hey @heymagurany, any chance you can make a test? I don't think I understand the problem well enough to make one.

**Comment by heymagurany** [comment]
@matthewp Sure thing. I'll get a test written and the conflicts resolved.

**Comment by eubnara** [comment]
I think this pull request needs to be done! #306 issue still exists.

**Comment by heymagurany** [comment]
I'm closing this PR since the setting the `decodeURLComponents` option to `false` fixes the linked issue.

**Pull request closed without merging**
