### PR TITLE
New release to incorporate path-to-regexp 1.2.1

### PR DESCRIPTION
**Pull request by woodlandhunter**
Pinging @shuvalov-anton per discussion in #315

Tests are passing: `108 passing (565ms)`

Thanks.

### CODE REVIEW

**Comment by shuvalov-anton** [comment]
Wow! It's great!

**Comment by rstacruz** [comment]
might as well enable greenkeeper.io for this repo :)

**Comment by shuvalov-anton** [comment]
@rstacruz Sounds good. Can you? :D

**Comment by shuvalov-anton** [comment]
@rstacruz and as I see, we have only `path-to-regexp`. Is autoupdate really good 'cause `path-to-regesp` is part of our public API?

**Comment by Dashed** [comment]
Can someone please release 1.6.4 to npm? Only 1.6.3 is listed: https://www.npmjs.com/package/page

**Pull request merged**
