### PR TITLE
Do not listen for the load event if the document is already loaded

### LINKED ISSUE #249: loaded check doesn't work if page.js is dynamically loaded
I found that popstate detection was broken in my project, but found nothing in the issues.
After a bit of tracing code, I found that the error comes from this piece of code:

*index.js:235*
```javascript
  var onpopstate = (function() {
    var loaded = false;
      window.addEventListener('load', function() {
        setTimeout(function() {
          loaded = true;
        }, 0);
      });
   ... code omitted ...
  })();

```

Because my project would dynamically load in page.js after complete page load, this event listener would never be fired. Perhaps check document.readyState before setting up an event listener for this case?

### PR DESCRIPTION
**Pull request by ahelmberger**
Resolves #249

### CODE REVIEW

**Comment by shuvalov-anton** [comment]
Thank you!

**Comment by ahelmberger** [comment]
You're very welcome. We enjoy page.js very much in one of our browser applications. Any chance we could see this change on npm soon?

**Comment by shuvalov-anton** [comment]
@ahelmberger  yes, I want to release it at weekends with fix for #256.

**Comment by ahelmberger** [comment]
Thank you!

**Pull request merged**
