### PR TITLE
Fix for page.js on NW.js on Windows

### PR DESCRIPTION
**Pull request by kethinov**
This check ensures that the leading "/C:" prepended to `el.pathname` in [NW.js](https://github.com/nwjs/nw.js) on Windows is stripped so that `el.pathname` returns the same value on all operating systems.

For instance in a NW.js app on Windows, if you write HTML like this:

```html
<a href='/somewhere'>Somewhere</a>
```

Then `el.pathname` in page.js is `/somewhere` in Linux/Mac, but returns `/C:/somewhere` in Windows.

This PR normalizes the path.

### CODE REVIEW

**Comment by kethinov** [comment]
Update: this could be any any drive letter. Might need a bit of regex here. I'll keep thinking about it and push an update to this PR. I'm open to suggestions.

**Comment by kethinov** [comment]
Okay, I updated this PR to use a regex version.

**Comment by shuvalov-anton** [comment]
@kethinov  Is it time to merge this PR?

**Comment by kethinov** [comment]
Yes, I think it's ready if you approve.

**Comment by shuvalov-anton** [comment]
Can you rebase it?

**Comment by kethinov** [comment]
Done.

**Comment by shuvalov-anton** [comment]
@kethinov oh, sorry, i meant `squash` commits into one, like by `rebase -i` %)

**Comment by kethinov** [comment]
I just reforked with a fresh PR: https://github.com/visionmedia/page.js/pull/238

**Pull request closed without merging**
