### PR TITLE
make page singleton

### PR DESCRIPTION
**Pull request by andineck**
When using page.js with browserify, it has got side effects.
Without this fix, is not possible to have distributed routes in
different modules.

### CODE REVIEW

**Comment by shuvalov-anton** [comment]
I thought, browserify always returns a reference to the same instance of the module. Can you show me example with this problem?

**Comment by andineck** [comment]
It is a general `common.js/node require` problem, that also occurs with `browserify`. See: http://nodejs.org/api/modules.html#modules_module_caching_caveats 

### Example 

browser.js:
```js
var page = require('page');
require('b'); // does not work
require('./lib/b'); // works
page();
```

node_modules/b/index.js
```js
var page = require('page');
// a different page function is created here
page('*', function() {
  console.log('b/index.js href', window.location.href);
});
```

lib/b.js
````js
var page = require('page');
page('*', function() {
  console.log('lib/b.js href', window.location.href);
});
```

**Comment by shuvalov-anton** [comment]
I got it. But how this fix should help us? If `require('page')` will return other module object, we lose `_page` variable.

**Comment by andineck** [comment]
Hmm, you are right, my "fix" does not help in any way. I tested it but it only worked, because I forgot to install `page` on the module `b`. 

What about adding a global `page` attribute?
```
module.exports = (window.page) ? window.page : page;
```

**Comment by shuvalov-anton** [comment]
mb you can use [`peerDependencies`](http://blog.nodejs.org/2013/02/07/peer-dependencies/)?

**Comment by andineck** [comment]
That's also an idea. Although maybe they will be deprecated in the future: https://github.com/npm/npm/issues/5080.

The longer I think of this problem I think it would be better not to depend on some sort of  `global` or `singleton`.  

Probably a clean solution for distributed routes with page routes in different modules would be, to have a `use()` function similar to the `express  app.use()` function where you can "join" different page.js routes into another one.

**Pull request closed without merging**
