### PR TITLE
use shadow dom when available

### PR DESCRIPTION
**Pull request by MWalid**
tested with chrome, safari and firefox.

### CODE REVIEW

**Comment by MWalid** [comment]
This fix will work with browsers which support shadow dom natively like google chrome and others that don't like safari ....

**Comment by StatelessCat** [comment]
This fix will be helpful, do you plan to integrate it soon?
Thanks.

**Comment by kunnix** [comment]
Tested locally with Polymer 1.2.3 and page.js 1.6.4:

 - Without this patch, page.js:

  - works well when shadow DOM is disabled.
  - doesn't work when shadow DOM is enabled.

 - With this patch, page.js:

  - works well when shadow DOM is disabled.
  - works well when shadow DOM is enabled.

Any plan to integrate it soon?

Thanks!

**Comment by rstacruz** [comment]
thanks!

**Pull request merged**
