### PR TITLE
Include ctx in page.after example (fixes #290)

### LINKED ISSUE #290: Doc in page.exit() is wrong
In https://github.com/visionmedia/page.js#pageexitpath-callback-callback- the example should have `ctx` as first argument:

```js
page.exit('/sidebar', function(ctx, next) {  // Instead of just (next)
  sidebar.open = false
  next()
})
```

### PR DESCRIPTION
**Pull request by aaronshaf**

### CODE REVIEW

**Comment by aaronshaf** [comment]
@shuvalov-anton, please see ^

**Comment by shuvalov-anton** [comment]
@aaronshaf Looks like it will break backward compatibility 'cause now all uses first param for `next`. We can make `ctx` optional if `arguments.length > 1`. This is kinda hacky but IMHO it is the only way to save backward compatibility. What do you think?

And one more question. Can you provide case for `ctx` in the exit method?

**Comment by aaronshaf** [comment]
Enter:

```ctx.unsubscribe = subscribe(yadda)```

On exit:

```ctx.unsubscribe()```

**Comment by aaronshaf** [comment]
page.exit already seems to include context (this is working my code). This PR is about documentation. 

>  We can make ctx optional if arguments.length > 1

Sounds good

**Comment by shuvalov-anton** [comment]
Lol! I've screwed up. Sorry for my mistake :D

**Pull request merged**
