### PR TITLE
Fix for Safari popstate issue, closes #213

### LINKED ISSUE #213: Popstate fired on initial page load causes double trigger (Safari 8)
Safari 8 is still firing a popstate event after the page is ready. This causes a second match to occur and triggers the current route to exit and return. Chrome, IE, and Firefox are all OK.

Should a check to ignore the initial stateless popstate in Safari be added?

### PR DESCRIPTION
**Pull request by kethinov**

### CODE REVIEW

**Comment by shuvalov-anton** [comment]
Thank you! :D

**Comment by shuvalov-anton** [comment]
@kethinov Strange bug. I try to use this fix with my app and it totally broke the back button in chrome. But I can't reproduce the bug with clear setup. Probably the `load` event isn't firing. I'm trying to debug it.

**Comment by kethinov** [comment]
That's weird. Let me make a sample app real quick and post it so I can show you what I was working with.

**Comment by shuvalov-anton** [comment]
Oh, I got it. I'd starting page by `setTimeout(function() { page.start(); }, 0)` to start it after init all my modules with routes. Stupid hack. I'm sorry to trouble you.

**Comment by kethinov** [comment]
No worries.

Here is the sample app I built though for reference: https://github.com/kethinov/page.js-sample-app

**Comment by shuvalov-anton** [comment]
But if anyone starts `page` after `load` is fired, they got a problem with disabled popstate handler. Probably, it isn't good

**Comment by kethinov** [comment]
That's true. One thing we could do avoid the side effects is this:

```js
    if (false !== options.popstate) {
      
      // this hack resolves https://github.com/visionmedia/page.js/issues/213
      if (document.readyState !== 'complete') {
        // load event has not fired
        window.addEventListener('load', function() {
          setTimeout(function() {
            window.addEventListener('popstate', onpopstate, false);
          }, 0);
        }, false);
      }
      else {
        // load event has fired
        window.addEventListener('popstate', onpopstate, false);
      }
    }
```

That should prevent the side effects, but we'll still have the original "double fire" Safari bug if the user loads page.js after the load event fires.

**Comment by shuvalov-anton** [comment]
yes, and it looks not like little hack :(

**Comment by kethinov** [comment]
Ultimately the popstate issue is Safari's fault. They implemented the standard wrong.

The proposed hack above could fix it for anyone loading page.js before the `load` event fires.

For anyone loading page.js after the `load` event fires, we could call it a known issue / wontfix / blame Safari. ;)

Unless we can come up with a solution that works across both contexts, but I'm not aware of one.

**Pull request merged**
