### PR TITLE
Prevent default link behaviour when hashbang: true and protocol is file:

### PR DESCRIPTION
**Pull request by kaisermann**
Fix for #492

### CODE REVIEW

**Comment by PaulMaly** [comment]
@matthewp Can we merge this PR to the new release as soon as it's possible?

**Comment by matthewp** [comment]
Need to get the code coverage passing first.

**Comment by kaisermann** [comment]
I've added a basic test for this behavior but I couldn't get it passing because the `href=""`s in `test-page.html` starts with a `./`, not a `/` and that seems to fail in this case. If I changed the contact href from `./contact` to `/contact` it works as expected but fails anywhere else.

**Comment by PaulMaly** [comment]
@matthewp  Can we somehow skip it?

**Comment by kaisermann** [comment]
I think the main problem with that test is because `./contact` results in a pathname of `/var/www/contact`, not `/contact` as it should. I've pushed a commit that changes a little bit the `_getBase` to get the `dirname` instead of the full path when protocol is `file:`.

**Comment by matthewp** [comment]
Skipping tests won't help with the code coverage will it?

**Comment by kaisermann** [comment]
I'm wrapping my head around on how to fix the coverage and I don't have much free time right now. @PaulMaly or @matthewp Can one of you guys help me with this :grin:? Otherwise, just give me some days!

**Comment by matthewp** [comment]
There might be something weird going on because other PRs are failing coverage too. If you'll just get the tests passing again I'll skip the coverage for now.

**Comment by kaisermann** [comment]
It is passing since 3a75d238d8d486876bbbdc26275ccee021a89d6d, but I don't undestand why it's failing on node 0.1:

image

I'm gonna try to fix this if it's possible

**Comment by kaisermann** [comment]
@matthewp I don't exactly know why the test for `node 0.1` is failling in travis. I've reproduced the same thing in a identical local environment: 


<details>

<summary>Local log</summary>

```
$ node --version; npm --version; nvm --version; npm run engine-deps; npm test                                                                   
v8.12.0
6.4.1
0.33.11

> page@1.10.2 engine-deps /home/kaisermann/Projects/Personal/page.js
> install-engine-dependencies


> page@1.10.2 test /home/kaisermann/Projects/Personal/page.js
> jshint index.js test/tests.js && mocha test/tests.js



  Html5 history navigation
    ✓ Should dispatch when going to a hash on same path
    on page load
      ✓ should invoke the matching callback
      ✓ should invoke the matching async callbacks
    on redirect
      ✓ should load destination page
      ✓ should work with short alias
      ✓ should load done within redirect
    on exit
      ✓ should run when exiting the page
      ✓ should run async callbacks when exiting the page
      ✓ should only run on matched routes
      ✓ should use the previous context
    no dispatch
      ✓ should use the previous context when not dispatching
    page.back
      ✓ should move back to history
      ✓ should decrement page.len on back()
      ✓ calling back() when there is nothing in the history should go to the given path
      ✓ calling back with nothing in the history and no path should go to the base
    ctx.querystring
      ✓ should default to ""
      ✓ should expose the query string
      ✓ should accommodate URL encoding
    ctx.pathname
      ✓ should default to ctx.path
      ✓ should omit the query string
      ✓ should accommodate URL encoding
    ctx.params
      ✓ should always be URL-decoded
      ✓ should be an object
    ctx.handled
      ✓ should skip unhandled redirect if exists
    links dispatcher
      ✓ should invoke the callback
      ✓ should handle trailing slashes in URL
      ✓ should handle trailing slashes in route
      ✓ should invoke the callback with the right params
      ✓ should not invoke the callback
      ✓ should not fire when navigating to a different domain
      ✓ works with shadow paths
    dispatcher
      ✓ should ignore query strings
      ✓ should ignore query strings with params
      ✓ should invoke the matching callback
      ✓ should handle trailing slashes in path
      ✓ should handle trailing slashes in route
      ✓ should populate ctx.params
      ✓ should not include hash in ctx.pathname
      when next() is invoked
        ✓ should invoke subsequent matching middleware
      not found
        ✓ should invoke the not found callback

  Configuration
    ✓ Can disable popstate
    ✓ Can disable click handler

  Hashbang option enabled
    ✓ Using hashbang, url's pathname not included in path
    on page load
      ✓ should invoke the matching callback
      ✓ should invoke the matching async callbacks
    on redirect
      ✓ should load destination page
      ✓ should work with short alias
      ✓ should load done within redirect
    on exit
      ✓ should run when exiting the page
      ✓ should run async callbacks when exiting the page
      ✓ should only run on matched routes
      ✓ should use the previous context
    no dispatch
      ✓ should use the previous context when not dispatching
    page.back
      ✓ should move back to history
      ✓ should decrement page.len on back()
      ✓ calling back() when there is nothing in the history should go to the given path
      ✓ calling back with nothing in the history and no path should go to the base
    ctx.querystring
      ✓ should default to ""
      ✓ should expose the query string
      ✓ should accommodate URL encoding
    ctx.pathname
      ✓ should default to ctx.path
      ✓ should omit the query string
      ✓ should accommodate URL encoding
    ctx.params
      ✓ should always be URL-decoded
      ✓ should be an object
    ctx.handled
      ✓ should skip unhandled redirect if exists
    links dispatcher
      ✓ should invoke the callback
      ✓ should handle trailing slashes in URL
      ✓ should handle trailing slashes in route
      ✓ should invoke the callback with the right params
      ✓ should not invoke the callback
      ✓ should not fire when navigating to a different domain
      ✓ works with shadow paths
    dispatcher
      ✓ should ignore query strings
      ✓ should ignore query strings with params
      ✓ should invoke the matching callback
      ✓ should handle trailing slashes in path
      ✓ should handle trailing slashes in route
      ✓ should populate ctx.params
      ✓ should not include hash in ctx.pathname
      when next() is invoked
        ✓ should invoke subsequent matching middleware
      not found
        ✓ should invoke the not found callback

  Different Base
    on page load
      ✓ should invoke the matching callback
      ✓ should invoke the matching async callbacks
    on redirect
      ✓ should load destination page
      ✓ should work with short alias
      ✓ should load done within redirect
    on exit
      ✓ should run when exiting the page
      ✓ should run async callbacks when exiting the page
      ✓ should only run on matched routes
      ✓ should use the previous context
    no dispatch
      ✓ should use the previous context when not dispatching
    page.back
      ✓ should move back to history
      ✓ should decrement page.len on back()
      ✓ calling back() when there is nothing in the history should go to the given path
      ✓ calling back with nothing in the history and no path should go to the base
    ctx.querystring
      ✓ should default to ""
      ✓ should expose the query string
      ✓ should accommodate URL encoding
    ctx.pathname
      ✓ should default to ctx.path
      ✓ should omit the query string
      ✓ should accommodate URL encoding
    ctx.params
      ✓ should always be URL-decoded
      ✓ should be an object
    ctx.handled
      ✓ should skip unhandled redirect if exists
    links dispatcher
      ✓ should invoke the callback
      ✓ should handle trailing slashes in URL
      ✓ should handle trailing slashes in route
      ✓ should invoke the callback with the right params
      ✓ should not invoke the callback
      ✓ should not fire when navigating to a different domain
      ✓ works with shadow paths
    dispatcher
      ✓ should ignore query strings
      ✓ should ignore query strings with params
      ✓ should invoke the matching callback
      ✓ should handle trailing slashes in path
      ✓ should handle trailing slashes in route
      ✓ should populate ctx.params
      ✓ should not include hash in ctx.pathname
      when next() is invoked
        ✓ should invoke subsequent matching middleware
      not found
        ✓ should invoke the not found callback

  URL path component decoding disabled
    on page load
      ✓ should invoke the matching callback
      ✓ should invoke the matching async callbacks
    on redirect
      ✓ should load destination page
      ✓ should work with short alias
      ✓ should load done within redirect
    on exit
      ✓ should run when exiting the page
      ✓ should run async callbacks when exiting the page
      ✓ should only run on matched routes
      ✓ should use the previous context
    no dispatch
      ✓ should use the previous context when not dispatching
    page.back
      ✓ should move back to history
      ✓ should decrement page.len on back()
      ✓ calling back() when there is nothing in the history should go to the given path
      ✓ calling back with nothing in the history and no path should go to the base
    ctx.querystring
      ✓ should default to ""
      ✓ should expose the query string
      ✓ should accommodate URL encoding
    ctx.pathname
      ✓ should default to ctx.path
      ✓ should omit the query string
      ✓ should accommodate URL encoding
    ctx.params
      ✓ should always be URL-decoded
      ✓ should be an object
    ctx.handled
      ✓ should skip unhandled redirect if exists
    links dispatcher
      ✓ should invoke the callback
      ✓ should handle trailing slashes in URL
      ✓ should handle trailing slashes in route
      ✓ should invoke the callback with the right params
      ✓ should not invoke the callback
      ✓ should not fire when navigating to a different domain
      ✓ works with shadow paths
    dispatcher
      ✓ should ignore query strings
      ✓ should ignore query strings with params
      ✓ should invoke the matching callback
      ✓ should handle trailing slashes in path
      ✓ should handle trailing slashes in route
      ✓ should populate ctx.params
      ✓ should not include hash in ctx.pathname
      when next() is invoked
        ✓ should invoke subsequent matching middleware
      not found
        ✓ should invoke the not found callback

  Strict path matching enabled
    on page load
      ✓ should invoke the matching callback
      ✓ should invoke the matching async callbacks
    on redirect
      ✓ should load destination page
      ✓ should work with short alias
      ✓ should load done within redirect
    on exit
      ✓ should run when exiting the page
      ✓ should run async callbacks when exiting the page
      ✓ should only run on matched routes
      ✓ should use the previous context
    no dispatch
      ✓ should use the previous context when not dispatching
    page.back
      ✓ should move back to history
      ✓ should decrement page.len on back()
      ✓ calling back() when there is nothing in the history should go to the given path
      ✓ calling back with nothing in the history and no path should go to the base
    ctx.querystring
      ✓ should default to ""
      ✓ should expose the query string
      ✓ should accommodate URL encoding
    ctx.pathname
      ✓ should default to ctx.path
      ✓ should omit the query string
      ✓ should accommodate URL encoding
    ctx.params
      ✓ should always be URL-decoded
      ✓ should be an object
    ctx.handled
      ✓ should skip unhandled redirect if exists
    links dispatcher
      ✓ should invoke the callback
      ✓ should handle trailing slashes in URL
      ✓ should handle trailing slashes in route
      ✓ should invoke the callback with the right params
      ✓ should not invoke the callback
      ✓ should not fire when navigating to a different domain
      ✓ works with shadow paths
    dispatcher
      ✓ should ignore query strings
      ✓ should ignore query strings with params
      ✓ should invoke the matching callback
      ✓ should handle trailing slashes in path
      ✓ should handle trailing slashes in route
      ✓ should populate ctx.params
      ✓ should not include hash in ctx.pathname
      when next() is invoked
        ✓ should invoke subsequent matching middleware
      not found
        ✓ should invoke the not found callback

  File protocol
    ✓ simple route call
    ✓ click routing


  201 passing (771ms)
```
<details>

**Comment by kaisermann** [comment]
> @matthewp I don't exactly know why the test for `node 0.1` is failling in travis. I've reproduced the same thing in a identical local environment:
> 
> Local log
> ```
> $ node --version; npm --version; nvm --version; npm run engine-deps; npm test                                                                   
> v8.12.0
> 6.4.1
> 0.33.11
> 
> > page@1.10.2 engine-deps /home/kaisermann/Projects/Personal/page.js
> > install-engine-dependencies
> 
> 
> > page@1.10.2 test /home/kaisermann/Projects/Personal/page.js
> > jshint index.js test/tests.js && mocha test/tests.js
> 
> 
> 
>   Html5 history navigation
>     ✓ Should dispatch when going to a hash on same path
>     on page load
>       ✓ should invoke the matching callback
>       ✓ should invoke the matching async callbacks
>     on redirect
>       ✓ should load destination page
>       ✓ should work with short alias
>       ✓ should load done within redirect
>     on exit
>       ✓ should run when exiting the page
>       ✓ should run async callbacks when exiting the page
>       ✓ should only run on matched routes
>       ✓ should use the previous context
>     no dispatch
>       ✓ should use the previous context when not dispatching
>     page.back
>       ✓ should move back to history
>       ✓ should decrement page.len on back()
>       ✓ calling back() when there is nothing in the history should go to the given path
>       ✓ calling back with nothing in the history and no path should go to the base
>     ctx.querystring
>       ✓ should default to ""
>       ✓ should expose the query string
>       ✓ should accommodate URL encoding
>     ctx.pathname
>       ✓ should default to ctx.path
>       ✓ should omit the query string
>       ✓ should accommodate URL encoding
>     ctx.params
>       ✓ should always be URL-decoded
>       ✓ should be an object
>     ctx.handled
>       ✓ should skip unhandled redirect if exists
>     links dispatcher
>       ✓ should invoke the callback
>       ✓ should handle trailing slashes in URL
>       ✓ should handle trailing slashes in route
>       ✓ should invoke the callback with the right params
>       ✓ should not invoke the callback
>       ✓ should not fire when navigating to a different domain
>       ✓ works with shadow paths
>     dispatcher
>       ✓ should ignore query strings
>       ✓ should ignore query strings with params
>       ✓ should invoke the matching callback
>       ✓ should handle trailing slashes in path
>       ✓ should handle trailing slashes in route
>       ✓ should populate ctx.params
>       ✓ should not include hash in ctx.pathname
>       when next() is invoked
>         ✓ should invoke subsequent matching middleware
>       not found
>         ✓ should invoke the not found callback
> 
>   Configuration
>     ✓ Can disable popstate
>     ✓ Can disable click handler
> 
>   Hashbang option enabled
>     ✓ Using hashbang, url's pathname not included in path
>     on page load
>       ✓ should invoke the matching callback
>       ✓ should invoke the matching async callbacks
>     on redirect
>       ✓ should load destination page
>       ✓ should work with short alias
>       ✓ should load done within redirect
>     on exit
>       ✓ should run when exiting the page
>       ✓ should run async callbacks when exiting the page
>       ✓ should only run on matched routes
>       ✓ should use the previous context
>     no dispatch
>       ✓ should use the previous context when not dispatching
>     page.back
>       ✓ should move back to history
>       ✓ should decrement page.len on back()
>       ✓ calling back() when there is nothing in the history should go to the given path
>       ✓ calling back with nothing in the history and no path should go to the base
>     ctx.querystring
>       ✓ should default to ""
>       ✓ should expose the query string
>       ✓ should accommodate URL encoding
>     ctx.pathname
>       ✓ should default to ctx.path
>       ✓ should omit the query string
>       ✓ should accommodate URL encoding
>     ctx.params
>       ✓ should always be URL-decoded
>       ✓ should be an object
>     ctx.handled
>       ✓ should skip unhandled redirect if exists
>     links dispatcher
>       ✓ should invoke the callback
>       ✓ should handle trailing slashes in URL
>       ✓ should handle trailing slashes in route
>       ✓ should invoke the callback with the right params
>       ✓ should not invoke the callback
>       ✓ should not fire when navigating to a different domain
>       ✓ works with shadow paths
>     dispatcher
>       ✓ should ignore query strings
>       ✓ should ignore query strings with params
>       ✓ should invoke the matching callback
>       ✓ should handle trailing slashes in path
>       ✓ should handle trailing slashes in route
>       ✓ should populate ctx.params
>       ✓ should not include hash in ctx.pathname
>       when next() is invoked
>         ✓ should invoke subsequent matching middleware
>       not found
>         ✓ should invoke the not found callback
> 
>   Different Base
>     on page load
>       ✓ should invoke the matching callback
>       ✓ should invoke the matching async callbacks
>     on redirect
>       ✓ should load destination page
>       ✓ should work with short alias
>       ✓ should load done within redirect
>     on exit
>       ✓ should run when exiting the page
>       ✓ should run async callbacks when exiting the page
>       ✓ should only run on matched routes
>       ✓ should use the previous context
>     no dispatch
>       ✓ should use the previous context when not dispatching
>     page.back
>       ✓ should move back to history
>       ✓ should decrement page.len on back()
>       ✓ calling back() when there is nothing in the history should go to the given path
>       ✓ calling back with nothing in the history and no path should go to the base
>     ctx.querystring
>       ✓ should default to ""
>       ✓ should expose the query string
>       ✓ should accommodate URL encoding
>     ctx.pathname
>       ✓ should default to ctx.path
>       ✓ should omit the query string
>       ✓ should accommodate URL encoding
>     ctx.params
>       ✓ should always be URL-decoded
>       ✓ should be an object
>     ctx.handled
>       ✓ should skip unhandled redirect if exists
>     links dispatcher
>       ✓ should invoke the callback
>       ✓ should handle trailing slashes in URL
>       ✓ should handle trailing slashes in route
>       ✓ should invoke the callback with the right params
>       ✓ should not invoke the callback
>       ✓ should not fire when navigating to a different domain
>       ✓ works with shadow paths
>     dispatcher
>       ✓ should ignore query strings
>       ✓ should ignore query strings with params
>       ✓ should invoke the matching callback
>       ✓ should handle trailing slashes in path
>       ✓ should handle trailing slashes in route
>       ✓ should populate ctx.params
>       ✓ should not include hash in ctx.pathname
>       when next() is invoked
>         ✓ should invoke subsequent matching middleware
>       not found
>         ✓ should invoke the not found callback
> 
>   URL path component decoding disabled
>     on page load
>       ✓ should invoke the matching callback
>       ✓ should invoke the matching async callbacks
>     on redirect
>       ✓ should load destination page
>       ✓ should work with short alias
>       ✓ should load done within redirect
>     on exit
>       ✓ should run when exiting the page
>       ✓ should run async callbacks when exiting the page
>       ✓ should only run on matched routes
>       ✓ should use the previous context
>     no dispatch
>       ✓ should use the previous context when not dispatching
>     page.back
>       ✓ should move back to history
>       ✓ should decrement page.len on back()
>       ✓ calling back() when there is nothing in the history should go to the given path
>       ✓ calling back with nothing in the history and no path should go to the base
>     ctx.querystring
>       ✓ should default to ""
>       ✓ should expose the query string
>       ✓ should accommodate URL encoding
>     ctx.pathname
>       ✓ should default to ctx.path
>       ✓ should omit the query string
>       ✓ should accommodate URL encoding
>     ctx.params
>       ✓ should always be URL-decoded
>       ✓ should be an object
>     ctx.handled
>       ✓ should skip unhandled redirect if exists
>     links dispatcher
>       ✓ should invoke the callback
>       ✓ should handle trailing slashes in URL
>       ✓ should handle trailing slashes in route
>       ✓ should invoke the callback with the right params
>       ✓ should not invoke the callback
>       ✓ should not fire when navigating to a different domain
>       ✓ works with shadow paths
>     dispatcher
>       ✓ should ignore query strings
>       ✓ should ignore query strings with params
>       ✓ should invoke the matching callback
>       ✓ should handle trailing slashes in path
>       ✓ should handle trailing slashes in route
>       ✓ should populate ctx.params
>       ✓ should not include hash in ctx.pathname
>       when next() is invoked
>         ✓ should invoke subsequent matching middleware
>       not found
>         ✓ should invoke the not found callback
> 
>   Strict path matching enabled
>     on page load
>       ✓ should invoke the matching callback
>       ✓ should invoke the matching async callbacks
>     on redirect
>       ✓ should load destination page
>       ✓ should work with short alias
>       ✓ should load done within redirect
>     on exit
>       ✓ should run when exiting the page
>       ✓ should run async callbacks when exiting the page
>       ✓ should only run on matched routes
>       ✓ should use the previous context
>     no dispatch
>       ✓ should use the previous context when not dispatching
>     page.back
>       ✓ should move back to history
>       ✓ should decrement page.len on back()
>       ✓ calling back() when there is nothing in the history should go to the given path
>       ✓ calling back with nothing in the history and no path should go to the base
>     ctx.querystring
>       ✓ should default to ""
>       ✓ should expose the query string
>       ✓ should accommodate URL encoding
>     ctx.pathname
>       ✓ should default to ctx.path
>       ✓ should omit the query string
>       ✓ should accommodate URL encoding
>     ctx.params
>       ✓ should always be URL-decoded
>       ✓ should be an object
>     ctx.handled
>       ✓ should skip unhandled redirect if exists
>     links dispatcher
>       ✓ should invoke the callback
>       ✓ should handle trailing slashes in URL
>       ✓ should handle trailing slashes in route
>       ✓ should invoke the callback with the right params
>       ✓ should not invoke the callback
>       ✓ should not fire when navigating to a different domain
>       ✓ works with shadow paths
>     dispatcher
>       ✓ should ignore query strings
>       ✓ should ignore query strings with params
>       ✓ should invoke the matching callback
>       ✓ should handle trailing slashes in path
>       ✓ should handle trailing slashes in route
>       ✓ should populate ctx.params
>       ✓ should not include hash in ctx.pathname
>       when next() is invoked
>         ✓ should invoke subsequent matching middleware
>       not found
>         ✓ should invoke the not found callback
> 
>   File protocol
>     ✓ simple route call
>     ✓ click routing
> 
> 
>   201 passing (771ms)
> ```

**Comment by kaisermann** [comment]
@matthewp I don't exactly know why the test for `node 0.1` is failling in travis. I've reproduced the same thing in a identical local environment: 


<details>

<summary>Local log</summary>

```
$ nvm use 0.10.48; node --version; npm --version; nvm --version; npm run engine-deps; npm test

Now using node v0.10.48 (npm v2.15.1)
v0.10.48
2.15.1
0.33.11

> page@1.10.2 engine-deps /home/kaisermann/Projects/Personal/page.js
> install-engine-dependencies


> page@1.10.2 test /home/kaisermann/Projects/Personal/page.js
> jshint index.js test/tests.js && mocha test/tests.js



  Html5 history navigation
    ✓ Should dispatch when going to a hash on same path
    on page load
      ✓ should invoke the matching callback
      ✓ should invoke the matching async callbacks
    on redirect
      ✓ should load destination page
      ✓ should work with short alias
      ✓ should load done within redirect
    on exit
      ✓ should run when exiting the page
      ✓ should run async callbacks when exiting the page
      ✓ should only run on matched routes
      ✓ should use the previous context
    no dispatch
      ✓ should use the previous context when not dispatching
    page.back
      ✓ should move back to history
      ✓ should decrement page.len on back()
      ✓ calling back() when there is nothing in the history should go to the given path
      ✓ calling back with nothing in the history and no path should go to the base
    ctx.querystring
      ✓ should default to ""
      ✓ should expose the query string
      ✓ should accommodate URL encoding
    ctx.pathname
      ✓ should default to ctx.path
      ✓ should omit the query string
      ✓ should accommodate URL encoding
    ctx.params
      ✓ should always be URL-decoded
      ✓ should be an object
    ctx.handled
      ✓ should skip unhandled redirect if exists
    links dispatcher
      ✓ should invoke the callback
      ✓ should handle trailing slashes in URL
      ✓ should handle trailing slashes in route
      ✓ should invoke the callback with the right params
      ✓ should not invoke the callback
      ✓ should not fire when navigating to a different domain
      ✓ works with shadow paths
    dispatcher
      ✓ should ignore query strings
      ✓ should ignore query strings with params
      ✓ should invoke the matching callback
      ✓ should handle trailing slashes in path
      ✓ should handle trailing slashes in route
      ✓ should populate ctx.params
      ✓ should not include hash in ctx.pathname
      when next() is invoked
        ✓ should invoke subsequent matching middleware
      not found
        ✓ should invoke the not found callback

  Configuration
    ✓ Can disable popstate
    ✓ Can disable click handler

  Hashbang option enabled
    ✓ Using hashbang, url's pathname not included in path
    on page load
      ✓ should invoke the matching callback
      ✓ should invoke the matching async callbacks
    on redirect
      ✓ should load destination page
      ✓ should work with short alias
      ✓ should load done within redirect
    on exit
      ✓ should run when exiting the page
      ✓ should run async callbacks when exiting the page
      ✓ should only run on matched routes
      ✓ should use the previous context
    no dispatch
      ✓ should use the previous context when not dispatching
    page.back
      ✓ should move back to history
      ✓ should decrement page.len on back()
      ✓ calling back() when there is nothing in the history should go to the given path
      ✓ calling back with nothing in the history and no path should go to the base
    ctx.querystring
      ✓ should default to ""
      ✓ should expose the query string
      ✓ should accommodate URL encoding
    ctx.pathname
      ✓ should default to ctx.path
      ✓ should omit the query string
      ✓ should accommodate URL encoding
    ctx.params
      ✓ should always be URL-decoded
      ✓ should be an object
    ctx.handled
      ✓ should skip unhandled redirect if exists
    links dispatcher
      ✓ should invoke the callback
      ✓ should handle trailing slashes in URL
      ✓ should handle trailing slashes in route
      ✓ should invoke the callback with the right params
      ✓ should not invoke the callback
      ✓ should not fire when navigating to a different domain
      ✓ works with shadow paths
    dispatcher
      ✓ should ignore query strings
      ✓ should ignore query strings with params
      ✓ should invoke the matching callback
      ✓ should handle trailing slashes in path
      ✓ should handle trailing slashes in route
      ✓ should populate ctx.params
      ✓ should not include hash in ctx.pathname
      when next() is invoked
        ✓ should invoke subsequent matching middleware
      not found
        ✓ should invoke the not found callback

  Different Base
    on page load
      ✓ should invoke the matching callback
      ✓ should invoke the matching async callbacks
    on redirect
      ✓ should load destination page
      ✓ should work with short alias
      ✓ should load done within redirect
    on exit
      ✓ should run when exiting the page
      ✓ should run async callbacks when exiting the page
      ✓ should only run on matched routes
      ✓ should use the previous context
    no dispatch
      ✓ should use the previous context when not dispatching
    page.back
      ✓ should move back to history
      ✓ should decrement page.len on back()
      ✓ calling back() when there is nothing in the history should go to the given path
      ✓ calling back with nothing in the history and no path should go to the base
    ctx.querystring
      ✓ should default to ""
      ✓ should expose the query string
      ✓ should accommodate URL encoding
    ctx.pathname
      ✓ should default to ctx.path
      ✓ should omit the query string
      ✓ should accommodate URL encoding
    ctx.params
      ✓ should always be URL-decoded
      ✓ should be an object
    ctx.handled
      ✓ should skip unhandled redirect if exists
    links dispatcher
      ✓ should invoke the callback
      ✓ should handle trailing slashes in URL
      ✓ should handle trailing slashes in route
      ✓ should invoke the callback with the right params
      ✓ should not invoke the callback
      ✓ should not fire when navigating to a different domain
      ✓ works with shadow paths
    dispatcher
      ✓ should ignore query strings
      ✓ should ignore query strings with params
      ✓ should invoke the matching callback
      ✓ should handle trailing slashes in path
      ✓ should handle trailing slashes in route
      ✓ should populate ctx.params
      ✓ should not include hash in ctx.pathname
      when next() is invoked
        ✓ should invoke subsequent matching middleware
      not found
        ✓ should invoke the not found callback

  URL path component decoding disabled
    on page load
      ✓ should invoke the matching callback
      ✓ should invoke the matching async callbacks
    on redirect
      ✓ should load destination page
      ✓ should work with short alias
      ✓ should load done within redirect
    on exit
      ✓ should run when exiting the page
      ✓ should run async callbacks when exiting the page
      ✓ should only run on matched routes
      ✓ should use the previous context
    no dispatch
      ✓ should use the previous context when not dispatching
    page.back
      ✓ should move back to history
      ✓ should decrement page.len on back()
      ✓ calling back() when there is nothing in the history should go to the given path
      ✓ calling back with nothing in the history and no path should go to the base
    ctx.querystring
      ✓ should default to ""
      ✓ should expose the query string
      ✓ should accommodate URL encoding
    ctx.pathname
      ✓ should default to ctx.path
      ✓ should omit the query string
      ✓ should accommodate URL encoding
    ctx.params
      ✓ should always be URL-decoded
      ✓ should be an object
    ctx.handled
      ✓ should skip unhandled redirect if exists
    links dispatcher
      ✓ should invoke the callback
      ✓ should handle trailing slashes in URL
      ✓ should handle trailing slashes in route
      ✓ should invoke the callback with the right params
      ✓ should not invoke the callback
      ✓ should not fire when navigating to a different domain
      ✓ works with shadow paths
    dispatcher
      ✓ should ignore query strings
      ✓ should ignore query strings with params
      ✓ should invoke the matching callback
      ✓ should handle trailing slashes in path
      ✓ should handle trailing slashes in route
      ✓ should populate ctx.params
      ✓ should not include hash in ctx.pathname
      when next() is invoked
        ✓ should invoke subsequent matching middleware
      not found
        ✓ should invoke the not found callback

  Strict path matching enabled
    on page load
      ✓ should invoke the matching callback
      ✓ should invoke the matching async callbacks
    on redirect
      ✓ should load destination page
      ✓ should work with short alias
      ✓ should load done within redirect
    on exit
      ✓ should run when exiting the page
      ✓ should run async callbacks when exiting the page
      ✓ should only run on matched routes
      ✓ should use the previous context
    no dispatch
      ✓ should use the previous context when not dispatching
    page.back
      ✓ should move back to history
      ✓ should decrement page.len on back()
      ✓ calling back() when there is nothing in the history should go to the given path
      ✓ calling back with nothing in the history and no path should go to the base
    ctx.querystring
      ✓ should default to ""
      ✓ should expose the query string
      ✓ should accommodate URL encoding
    ctx.pathname
      ✓ should default to ctx.path
      ✓ should omit the query string
      ✓ should accommodate URL encoding
    ctx.params
      ✓ should always be URL-decoded
      ✓ should be an object
    ctx.handled
      ✓ should skip unhandled redirect if exists
    links dispatcher
      ✓ should invoke the callback
      ✓ should handle trailing slashes in URL
      ✓ should handle trailing slashes in route
      ✓ should invoke the callback with the right params
      ✓ should not invoke the callback
      ✓ should not fire when navigating to a different domain
      ✓ works with shadow paths
    dispatcher
      ✓ should ignore query strings
      ✓ should ignore query strings with params
      ✓ should invoke the matching callback
      ✓ should handle trailing slashes in path
      ✓ should handle trailing slashes in route
      ✓ should populate ctx.params
      ✓ should not include hash in ctx.pathname
      when next() is invoked
        ✓ should invoke subsequent matching middleware
      not found
        ✓ should invoke the not found callback

  File protocol
    ✓ simple route call
    ✓ click routing


  201 passing (794ms)
```
</details>

**Comment by kaisermann** [comment]
@matthewp I've managed to reproduce the failing test for `node 0.1` but couldn't find an exact reason because it works fine for `node 6+`. Could it be related to an old version of `jsdom`? `Node 6+` seems to install version `11.12.0` while `Node 0.1` installs `1.5.0`.

**Comment by PaulMaly** [comment]
@matthewp Maybe we can skip failing tests for this PR?

**Comment by kaisermann** [comment]
@PaulMaly The tests are passing now (if you disconsider node 0.1 :grin:)

**Comment by PaulMaly** [comment]
@kaisermann awesome, but it’s still not in release ((

**Comment by matthewp** [comment]
We can't skip failing tests. We can skip the code coverage since I think there is something weird happening there.  If you branch straight off of master does the old Node version work?

**Comment by kaisermann** [comment]
Yes it works on master, but it doesn't have the test for resolving a clicked `<a>` when protocol is `file://`. 

I was trying to debug the `jsdom` `1.3.1` and it seems it doesn't resolve the URL correctly:

```> page@1.10.2 test /home/kaisermann/Projects/Personal/page.js
> jshint index.js test/tests.js && mocha test/tests.js

  File protocol
Resolving <a> HREF: about:blank
Base Url: http://example.com
Href:  about:blank
JSDOM Intermediate:  about:blank
Final resolved href:  about:blank

Resolving <a> HREF: ./contact
Base Url: about:blank
Href:  ./contact
JSDOM Intermediate:  about:contact
Final resolved href:  about:contact

Resolving <a> HREF: ./contact
Resolving <a> HREF: about:contact
Base Url: about:blank
Href:  about:contact
JSDOM Intermediate:  about:contact
Final resolved href:  about:contact

Resolving <a> HREF: about:contact
```

All these logs are from the last test in `test.js`. I've put those logs inside the `jsdom` `resolve` method. Maybe it's a configuration issue since there's those `about:blank` paths. 

Anyway, the failing test for `node 0.1` seems to be caused by `jsdom` resolving the `./contact` path to `about:contact`.

**Comment by matthewp** [comment]
Yeah, so it's because of your added test. So let's do this: remove that test. We'll ignore codecoverage and get this in.

**Comment by matthewp** [comment]
This was released in 1.11.0

**Pull request merged**
