### PR TITLE
Few conditions to improve nodejs support

### PR DESCRIPTION
**Pull request by PaulMaly**

### CODE REVIEW

**Comment by PaulMaly** [comment]
Made the code is a little bit pretty.

**Comment by matthewp** [comment]
Perfect, thank you! Would be interested in how you are using page.js in Node. I might want to add a few Node tests in the future. Maybe create an issue?

**Comment by matthewp** [comment]
I plan on doing a patch release tomorrow btw.

**Comment by PaulMaly** [comment]
@matthewp Thanks, it would be great. I'm glad that I able to come back to the main repo. 

> Would be interested in how you are using page.js in Node. I might want to add a few Node tests in the future. Maybe create an issue?

Sure, but nothing special there.

**Comment by matthewp** [comment]
1.7.2 is out and contains this fix: https://github.com/visionmedia/page.js/releases/tag/1.7.2

**Comment by PaulMaly** [comment]
@matthewp Thanks!

**Pull request merged**
