### PR TITLE
Adding property for previous route

### PR DESCRIPTION
**Pull request by jmisavage**
I found it useful on occasion to know the previous route in addition to the current one.

### CODE REVIEW

**Comment by vlkosinov** [comment]
+1

**Comment by dman777** [comment]
Wow, I could use this.

**Comment by matthewp** [comment]
Wouldn't it be better if this were on the context?

**Comment by paulocoghi** [comment]
> Wouldn't it be better if this were on the context?

I have the same opinion.

**Comment by jmisavage** [comment]
Closing this since its out of date

**Pull request closed without merging**
